apiVersion: v2
publisher: Integration TMMs
name: vscode-apache-camel-dil-streaming
version: 0.0.1
type: VS Code extension
displayName: Fleur De Lune
title: DIL Streaming Workshop
description: This VS Code extension provides support for Apache Camel for DIL Streaming
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/camel-tooling/camel-lsp-client-vscode
category: Language
firstPublicationDate: "2020-03-02"
deprecate:
  automigrate: true
  migrateTo: redhat/vscode-apache-camel/latest
spec:
  containers:
    - image: "quay.io/weimeilin79/dilws:latest"
      name: dil-ws
      memoryLimit: "2G"
  extensions:
    - https://github.com/camel-tooling/camel-lsp-client-vscode/releases/download/0.0.14/camel-tooling.vscode-apache-camel-0.0.14.vsix