:walkthrough: Cloud-Native Integration with EIPs
:enmasse-url: https://blah
:terminal-url: https://terminal-terminal.{openshift-app-host}/hub/user/{user-username}
:che-url: http://che-che.{openshift-app-host}/
:next-lab-url: https://tutorial-web-app-webapp.{openshift-app-host}/tutorial/dayinthelife-streaming.git-labs-04/
:user-password: openshift

ifdef::env-github[]
:next-lab-url: ../lab04/walkthrough.adoc
endif::[]

[id='cloud-native-integration']
= Lab 3 - Cloud-Native Integration with EIPs

In this lab you will stream events from an AMQ Online topic, use Enterprise Integration Patterns (EIPs) in Camel-K to split and route messages to a Datalake, in addition to streaming the messages to a Standard and Premium Shipping topic on Kafka.

Audience: Enterprise Integrators, System Architects, Developers, Data Integrators

*Overview*

Apache Kafka is the de facto standard for asynchronous event propagation between microservices. Things get challenging, though, when adding a service’s database to the picture: how can you avoid inconsistencies between Kafka and the database?

Enter change data capture (CDC) and Debezium. By capturing changes from the log files of the database, Debezium gives you both reliable and consistent inter-service messaging via Kafka and instant read-your-own-write semantics for services themselves.

*Why Red Hat?*

To respond to business demands quickly and efficiently, you need a way to integrate applications and data spread across your enterprise. Red Hat® AMQ—based on open source communities like Apache ActiveMQ and Apache Kafka—is a flexible messaging platform that delivers information reliably, enabling real-time integration and connecting the Internet of Things (IoT).

AMQ streams component makes Apache Kafka “OpenShift native” through the use of powerful operators that simplify the deployment, configuration, management, and use of Apache Kafka on OpenShift.

*Skipping The Lab*

*Credentials*

Your username is: `{user-username}` +
Your password is: `{user-password}`

[type=walkthroughResource]
.Amq
****
* link:{enmasse-url}/[Open AMQ Online, window="_blank"]
****

[type=walkthroughResource]
.Che
****
* link:{che-url}/[Open Eclipse Che, window="_blank"]
****

[type=walkthroughResource,serviceName=openshift]
.Openshift
****
* link:{openshift-host}/[Open Console, window="_blank"]
****

[type=walkthroughResource]
.Terminal
****
* link:{terminal-url}/[Open Terminal, window="_blank"]
****

[time=10]
[id="develop-camel-k"]
== This is a getting started lab, learn what is Camel K and get familiar with Che

. Navigate to the AMQ Online console: {enmasse-url}[AMQ Online, window="_blank", id="{context}-3"]
. Login to AMQ Online using your credentials.
. Create a topic on AMQ Online called `mytopic`.
. Navigate to Eclipse Che console: {che-url}[Eclipse Che, window="_blank", id="{context}-3"]
. Login to Che, see workspace.
. Get the AMQ Online address for userX. Update the config Map Create the config map.
+
[source,bash,subs="attributes+"]
----
oc create configmap edge-config  --from-file=edge.properties
camel.component.amqp.configuration.connection-factory.remoteURI=amqp://messaging-yez4fz7xkj.workshop-operators.svc:5672?amqp.saslMechanisms=PLAIN
----

. Start the simulator
+
[source,bash,subs="attributes+"]
----
kamel run --name edge-simulator EdgeSimulator.java  -d camel-jackson -d camel-bean  --configmap edge-config
----

[type=verification]
Were you able to successfuly run the Edge Simulator using Camel-K?

[type=verificationFail]
Verify that you followed each step in the procedure above. If you are still having issues, contact your administrator.

[time=5]
[id="summary"]
== Summary

In this lab you used Debezium CDC connectors to react to change events from SQL Server and send them to Apache Kafka running on OpenShift through Red Hat AMQ streams.

Open source connectors enable integrations with your local systems landscape. Explore Kafka, Camel, and Debezium connectors to connect APIs and services for event-driven application architectures (EDA). Red Hat offers supported versions of these connectors via AMQ Streams and Fuse.

You can now proceed to link:{next-lab-url}[Lab 3].

[time=4]
[id="further-reading"]
== Notes and Further Reading

* https://www.redhat.com/en/technologies/jboss-middleware/amq[Red Hat AMQ]
* https://developers.redhat.com/topics/event-driven/connectors/[Camel & Debezium Connectors]
