apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium
spec:
  bootstrapServers: 'earth-cluster-kafka-bootstrap.shared-kafka-earth.svc:9092'
  image: 'quay.io/hguerreroo/debezium-connect:0.10.0-sqlsrv'
  replicas: 1
  config:
    group.id: userX-connect-cluster
    offset.storage.topic: userX-connect-cluster-offsets
    config.storage.topic: userX-connect-cluster-configs
    status.storage.topic: userX-connect-cluster-status