---
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
  labels:
    app: "camel-k"
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: inventory-events
spec:
  configuration:
    - type: configmap
      value: amqp-properties
  dependencies:
    - 'camel:amqp'
    - 'camel:jackson'
  sources:
    - content: >-
        const Processor = Java.type("org.apache.camel.Processor");
        const p = Java.extend(Processor);
        const proc = new p(processInventory);
        from('amqp:topic:incomingorders?exchangePattern=InOnly')
            .log('Inventory Notified ${body}')
            .unmarshal().json()
            .setHeader('reply-to').simple('${body[username]}')
            .marshal().json()
            .delay(5000).asyncDelayed()
            .process(proc)
            .toD('amqp:topic:notifications?exchangePattern=InOnly')
            .to('log:info');
        function processInventory(e) {
            var order = JSON.parse(
                String.fromCharCode.apply(String, e.getMessage().getBody())
            );
            var result = JSON.stringify({
                orderId: order.orderId,
                itemId: order.itemId,
                department: 'inventory',
                datetime: Date.now(),
                quantity: order.quantity,
                flavor: order.orderItemName,
                inventoryId: Math.floor(100000 + Math.random() * 999999)
            });
            e.getMessage().setBody(result);
        }
      name: InventoryEvents.js
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: invoice-events
spec:
  configuration:
    - type: configmap
      value: amqp-properties
  dependencies:
    - 'camel:jackson'
    - 'camel:amqp'
  sources:
    - content: >-
        const Processor = Java.type("org.apache.camel.Processor");
        const p = Java.extend(Processor);
        const proc = new p(processInvoice);
        
        from('amqp:topic:incomingorders?exchangePattern=InOnly')
            .log('Invoicing Notified ${body}')
            .unmarshal().json()
            .marshal().json()
            .delay(10000).asyncDelayed()
            .process(proc)
            .log('H:${headers}')
            .toD('amqp:topic:notifications?exchangePattern=InOnly')
            .to('log:info');
            
        function processInvoice(e) {
            var order = JSON.parse(
                String.fromCharCode.apply(String, e.getMessage().getBody())
            );
            var result = JSON.stringify({
                orderId: order.orderId,
                itemId: order.itemId,
                department: 'invoicing',
                datetime: Date.now(),
                amount: (order.quantity*order.price),
                currency: 'USD',
                invoiceId: (Math.floor(100000 + Math.random() * 999999))
            });
            e.getMessage().setBody(result);
        }

        
      name: InvoiceEvents.js